import "./globals.css";

import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { NuqsAdapter } from "nuqs/adapters/next/app";

import Footer from "@/components/common/footer";
import Header from "@/components/common/header";
import { Toaster } from "@/components/ui/sonner";
import ReactQueryProvider from "@/providers/react-query";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <NuqsAdapter>
          <ReactQueryProvider>
            <Header className="sticky top-0" />
            {children}
            <div className="mt-12">
              <Footer className="sticky bottom-0" />
            </div>
          </ReactQueryProvider>
        </NuqsAdapter>

        <Toaster position="top-center" />
      </body>
    </html>
  );
}
